force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>store and manage individual job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>A date field to specify when to follow up on the application.</description>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVED</fullName>
                <default>true</default>
                <label>SAVED</label>
            </value>
            <value>
                <fullName>APPLYING</fullName>
            </value>
            <value>
                <fullName>APPLIED</fullName>
            </value>
            <value>
                <fullName>NEGOTIATING</fullName>
            </value>
            <value>
                <fullName>ACCEPTED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FollowupFieldUpdate.cls
public with sharing class FollowupFieldUpdate {
    public static void updateFollowupField(List<Job_Application__c> jobApplicationList, Map<Id, Job_Application__c> oldJobApps) {
        //Set<String> skipStatuses = new Set<String>{ 'Accepted', 'Closed','Saved' };
        for (Job_Application__c ja: jobApplicationList) {
             String st = ja.Status__c;
            if ( String.isBlank(st) || st.contains('SAVED') || st.contains('Saved') || ja.Status__c == oldJobApps.get(ja.Id).Status__c ) {
                continue;
            } ja.Follow_Up_Date__c = Date.today().addDays(4);
            
        }
    }
}