force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>store and manage individual job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>A date field to specify when to follow up on the application.</description>
    <label>Follow-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVED</fullName>
                <default>true</default>
                <label>SAVED</label>
            </value>
            <value>
                <fullName>APPLYING</fullName>
            </value>
            <value>
                <fullName>APPLIED</fullName>
            </value>
            <value>
                <fullName>NEGOTIATING</fullName>
            </value>
            <value>
                <fullName>ACCEPTED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StaleJobAppBatch.cls
public with sharing class StaleJobAppBatch implements Database.Batchable<sObject> {
    private Date cutoff = Date.today().addDays(-30);

    public Database.QueryLocator start(Database.BatchableContext bc){
        return database.getQueryLocator([SELECT Id, Status__c, Follow_up_Date__c, Notes__c 
        FROM Job_Application__c 
        WHERE Status__c NOT IN('Closed','Accepted') 
        AND Follow_up_Date__c <= :cutoff]);
    }

    public void execute(Database.BatchableContext bc, List<Job_Application__c> scope){
        List<Job_Application__c> toUpdate = new List<Job_Application__c>();

        for (Job_Application__c ja : scope) {
            ja.Status__c = 'Closed';
            ja.Notes__c = 'Closed by automated process on ' +  Date.today();
            toUpdate.add(ja);
        }

        if (!toUpdate.isEmpty()) {
            update toUpdate;
        }
    }

    public void finish(Database.BatchableContext bc){}


}