force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>store and manage individual job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Bi_annual_Pay__c.field-meta.xml
<CustomField>
    <fullName>Bi_annual_Pay__c</fullName>
    <label>Bi-annual Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Bi_weekly_Pay__c.field-meta.xml
<CustomField>
    <fullName>Bi_weekly_Pay__c</fullName>
    <label>Bi-weekly Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Federal_Income_Tax__c.field-meta.xml
<CustomField>
    <fullName>Federal_Income_Tax__c</fullName>
    <label>Federal Income Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Medicare_Withholding__c.field-meta.xml
<CustomField>
    <fullName>Medicare_Withholding__c</fullName>
    <label>Medicare Withholding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Monthly_Take_home_Pay__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Take_home_Pay__c</fullName>
    <label>Monthly Take-home Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>expected salary for the job position.</description>
    <label>Salary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Social_Security__c.field-meta.xml
<CustomField>
    <fullName>Social_Security__c</fullName>
    <label>Social Security</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Yearly_Take_home_Pay__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Take_home_Pay__c</fullName>
    <label>Yearly Take-home Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medicare_Settings__mdt/Medicare_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Medicare Settings</label>
    <pluralLabel>Medicare Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Social_Security_Settings__mdt/Social_Security_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Social Security Settings</label>
    <pluralLabel>Social Security Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Social_Security_Settings__mdt/fields/Wage_Base__c.field-meta.xml
<CustomField>
    <fullName>Wage_Base__c</fullName>
    <label>Wage Base</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standard_Deduction__mdt/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <label>Default</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Bracket__mdt/Tax_Bracket__mdt.object-meta.xml
<CustomObject>
    <label>Tax Bracket</label>
    <pluralLabel>Tax Brackets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Bracket__mdt/fields/Filing_Status__c.field-meta.xml
<CustomField>
    <fullName>Filing_Status__c</fullName>
    <label>Filing Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Bracket__mdt/fields/Lower_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Lower_Threshold__c</fullName>
    <label>Lower Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Bracket__mdt/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>9</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Bracket__mdt/fields/Upper_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Upper_Threshold__c</fullName>
    <label>Upper Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TakehomePayEstimatorHandler.cls
public with sharing class TakehomePayEstimatorHandler {
    public static void calcTakehomePay(List<Job_Application__c> jobApplications,Map<Id, Job_Application__c> oldMap) {
        //Salary
        //Standard Deduction
        //Taxable income
        //Tax Rate
        List<Job_Application__c>appsWithSalary = new List<Job_Application__c>();
        for (Job_Application__c ja : jobApplications) {
            //check is old value and new value id the same
            if(ja.Salary__c != null && (oldMap == null || !oldMap.containsKey(ja.Id) || ja.Salary__c != oldMap.get(ja.Id).Salary__c)){
               
                appsWithSalary.add(ja);
            }
        }
        if (appsWithSalary.isEmpty()) {
           return; 
        }

        

        Standard_Deduction__mdt sd = Standard_Deduction__mdt.getInstance('Default');
        Decimal sdDeduction = sd.Default__c;

        Social_Security_Settings__mdt ss = Social_Security_Settings__mdt.getInstance('Default');
        Decimal ssRate = ss.Rate__c;
        Decimal ssWageBase = ss.Wage_Base__c;

        Medicare_Settings__mdt ms = Medicare_Settings__mdt.getInstance('Default');
        Decimal msRate = ms.Rate__c;

        List<Tax_Bracket__mdt> br = [SELECT Lower_Threshold__c,Upper_Threshold__c,Rate__c,	Filing_Status__c FROM Tax_Bracket__mdt where Filing_Status__c = 'Single' ORDER BY Lower_Threshold__c];

        for (Job_Application__c jApp : appsWithSalary) {
           Decimal taxableIncome = jApp.Salary__c - sdDeduction;
           if (taxableIncome < 0) {
              taxableIncome = 0;
           }
               Decimal fed  = 0;
           
             for (Tax_Bracket__mdt tb : br) {
                Decimal low = TB.Lower_Threshold__c;
                Decimal high = tb.Upper_Threshold__c != null ? tb.Upper_Threshold__c : taxableIncome;
                if (taxableIncome > low) {
                    Decimal taxcut = Math.min(taxableIncome,high) - low;
                    fed += taxcut * tb.Rate__c;
                }
                if (taxableIncome <= high) {
                    break;
                }
             }
             fed = fed.setScale(2);
              
              Decimal ssTaxable  = Math.min(jApp.Salary__c, ssWageBase);
              Decimal ssTax = (ssTaxable * ssRate).setScale(2);
              Decimal mc   = (jApp.Salary__c * msRate).setScale(2);
              Decimal annualTakehome = (jApp.Salary__c - (fed + ssTax + mc)).setScale(2);
              Decimal biAnnualTakehome = (annualTakehome / 2).setScale(2);
              Decimal monthlyTakehome = (annualTakehome / 12).setScale(2);
              Decimal biWeeklyPay = (annualTakehome / 26).setScale(2);

            
           jApp.Federal_Income_Tax__c = fed;
           jApp.Medicare_Withholding__c = mc;
           jApp.Social_Security__c = ssTax;
           jApp.Yearly_Take_home_Pay__c = annualTakehome;
           jApp.Monthly_Take_home_Pay__c = monthlyTakehome;
           jApp.Bi_annual_Pay__c = biAnnualTakehome;
           jApp.Bi_weekly_Pay__c = biWeeklyPay;
           
        }

    }

    // Private static Decimal calculateFederalIncomeTax(Decimal taxableIncome){

    // }
}