force-app/main/default/objects/Contact/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>store and manage individual job applications</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The company where the job application is being sent.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>the main point of contact for the job.</description>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PrimaryContactUpdate.cls
public with sharing class PrimaryContactUpdate {
     public static void primaryContactFieldUpdate(List<Job_Application__c> jobApplications) {
            List<Job_Application__c> jobAppsNoPc = new List<Job_Application__c>();
        for (Job_Application__c jobApp : jobApplications) {
            if (jobApp.Primary_Contact__c == null ) {
                jobAppsNoPc.add(jobApp);
            }
        }

        if (jobAppsNoPc.isEmpty()) {
            return;
        }

        //Check if there are contacts related to the job application
        List<Contact> contacts = [SELECT Id, FirstName,LastName,Job_Application__c FROM Contact WHERE Job_Application__c IN :jobAppsNoPc];
       Map<Id, Contact> jobAppToContactMap = new Map<Id, Contact>();
       if (contacts != null && !contacts.isEmpty()) {
        for (Contact c : contacts) {
            if (c.job_Application__C != null && !jobAppToContactMap.containsKey(c.Job_Application__c)) {
                jobAppToContactMap.put(c.Job_Application__c, c);
            }
        }
       }
       
    // Check if there are Contacts related to the Account of the Job Application
    List<Job_Application__c> apps = [SELECT Id, CompanyName__c FROM Job_Application__c WHERE Id IN :jobAppsNoPc];   
    Map<Id, Account> jobAppToAccountMap = new Map<Id, Account>([SELECT Id, Name, (SELECT FirstName, LastName FROM Contacts LIMIT 1)  FROM Account WHERE Id IN (SELECT CompanyName__c FROM Job_Application__c WHERE Id IN :apps)]);
    Map<Id, Contact> jobAppToContact = new Map<Id, Contact>();
    for (Job_Application__c ja : apps) {
        Account acc = jobAppToAccountMap.get(ja.CompanyName__c );
         if (acc != null && !acc.Contacts.isEmpty()) {
          jobAppToContact.put(ja.Id, acc.Contacts[0]);
  }
}  


        for (Job_Application__c jobs : jobAppsNoPc) {
            if (jobAppToContactMap.containsKey(jobs.Id)) {
                jobs.Primary_Contact__c = jobAppToContactMap.get(jobs.Id).Id;
            } else {
                 if (jobAppToContact.containsKey(jobs.Id)) {
                  jobs.Primary_Contact__c = jobAppToContact.get(jobs.Id).Id;
                }
        
    }
}
}
}